<?php

return [
    'main_title' => 'General Terms and Conditions (GTC)',
    'first_title' => 'Scope of Application',
    'first_content_1' => '1. Scope of Application
        1.1 These General Terms and Conditions (GTC) apply to all business relationships
        between SVControl UG (Seller) and our customers ("Buyers").',
    'first_content_2' => '1.2 The General Terms and Conditions apply only if the Buyer is an entrepreneur (§ 14 BGB),
        a legal entity of public law, or a special fund under public law within the meaning of § 310 paragraph 1 BGB.',
    'first_content_3' => '1.3 Our General Terms and Conditions apply exclusively. Deviating,
        conflicting, or supplementary General Terms and Conditions of the Buyer become part of the contract only to the extent that we have expressly agreed to their validity. This requirement for consent also applies if the Buyer refers to his GTC in the context of the order and we have not expressly objected to the GTC.',
    
        'second_title' => 'Offer and Conclusion of Contract',
        'second_content_1' => '2.1 Our offers are subject to change and non-binding. We reserve ownership and copyright of all documents provided to the Buyer in connection with the order. These documents may not be made accessible to third parties unless we give the Buyer our express written consent.',
        'second_content_2' => '2.2 The Buyer\'s order constitutes a non-binding contract offer according to § 145 BGB and is considered accepted with a written order confirmation by SVControl.',
        'second_content_3' => '2.3 The responsibility for obtaining import and export licenses, currency permits, or similar necessary permissions for executing the contract lies with the Buyer. The Buyer must ensure that all required licenses, permits, or other export documents are obtained and presented in time to ensure timely export. In case of failure or delay in contract execution due to missing permissions, the Buyer bears the disadvantages and all associated costs.',
        'second_content_4' => '2.4 If the contract is terminated due to the Buyer\'s fault, the Seller is entitled to demand compensation from the Buyer in the form of 17% of the net purchase price as damages, in addition to compensation for the actual damage incurred, without this excluding the Seller\'s right to fulfillment.',
        

        'third_title' => 'Prices and Payment Agreements',
        'third_content_1' => '3.1 The costs of packaging will be billed separately. If no fixed price agreement has been made, reasonable price changes due to changed wage, material, and distribution costs for deliveries occurring 3 months or later after the conclusion of the contract are reserved.',
        'third_content_2' => '3.2 Payments by the Buyer, unless expressly agreed otherwise, are to be made to the payment office of SVControl, in EURO. If the Buyer does not pay by then, default occurs without further reminder. Invoicing is as follows: 30% at the time of order, within 10 days of invoicing; 70% upon notification of completion. The total payment must in any case be made before delivery of the goods.',
        'third_content_3' => '3.3 The Buyer is prohibited from withholding payments due to warranty claims or other counterclaims not accepted by the Seller.',
        'third_content_4' => '3.4 The Buyer may only offset if his counterclaims have been legally established, are undisputed, or have been recognized by SVControl. The Buyer does not have the right to withhold services due to disputed counterclaims.',
        'third_content_5' => '3.5 Without prior written permission from SVControl, the Buyer may not transfer or otherwise dispose of his claims against SVControl, either in whole or in part. The collection of partial amounts by third parties is not permitted.',
        

        'fifth_title' => 'Delivery Period and Delay in Delivery',
        'fifth_content_1' => '5.1 The delivery period is agreed individually and begins with the receipt of the agreed down payment and upon acceptance of the order.',
        'fifth_content_2' => '5.2 The delivery period will be appropriately extended if unforeseeable events occur. These include cases of force majeure, operational disruptions, strikes, lockouts, production of defective products, as well as delays in the delivery of essential raw and building materials or components crucial for the correct manufacturing of the products. In these cases, the Buyer is not allowed to withdraw from the contract due to the delayed delivery or demand damages from the Seller.',
        'fifth_content_3' => '5.3 If the Buyer fails to accept the goods on time and the Seller insists on delivering the goods, the Seller has the right to store the goods either on its own property or that of a third party. In this case, the Buyer must pay a reasonable storage fee that accrues daily, as well as any applicable transport and insurance costs. The Seller is not obligated to store the goods under special conditions or to insure the goods for the duration of storage.',
        'fifth_content_4' => '5.4 The delivery period is considered fulfilled if the goods have left the factory by the end of this period. If a non-binding delivery date or delivery period is exceeded by three weeks, the Buyer has the right to request SVControl in writing to deliver within a reasonable period. After the expiration of this period, the Seller is in default.',
        
        'sixth_title' => 'Transfer of Risk, Acceptance, Delay in Acceptance',
        'sixth_content_1' => '6.1 Should there be a delay in delivery that is not attributable to SVControl, the risk transfers to the Buyer on the day they are informed of the readiness for shipment.',
        'sixth_content_2' => '6.2 Upon the handover of the goods to the Buyer, the risk of accidental loss and accidental deterioration of the goods transfers to the Buyer. In the case of a sale by dispatch, the risk of accidental loss of the goods, accidental deterioration of the goods, and delay risk transfers to the carrier or freight forwarder upon delivery of the goods. In the event of a contractual agreement for the acceptance of the goods, this is decisive for the transfer of risk. Further legal provisions of contract law remain unaffected. The handover or acceptance of the goods is deemed equivalent if the Buyer is in default of acceptance.',
        'sixth_content_3' => '6.3 Shipment by SVControl only occurs if explicitly requested by the Buyer. Unless otherwise agreed in writing, shipping and transport are at the expense and risk of the Buyer, at the discretion of SVControl. In this case, SVControl insures the freight at the request and expense of the Buyer. Unless otherwise stated in the order confirmation, delivery is "ex works" (EXW) according to INCOTERMS 2010.',
        'sixth_content_4' => '6.4 Delay in acceptance by the Buyer entitles the Seller to demand immediate payment of his contractual claims, regardless of previously agreed payment terms.',
        'sixth_content_5' => '6.5 In the event of a delivery delay not attributable to SVControl, any risk transfers to the Buyer on the day of notification of readiness to ship.',

        'seventh_title' => 'Retention of Title',
        'seventh_content_1' => '7.1 We retain ownership of the delivered goods until the complete payment of all our present and future claims arising from the purchase contract and an ongoing business relationship (secured claims).',
        'seventh_content_2' => '7.2 Until the complete payment of the secured claims has been made, the goods subject to retention of title may not be pledged to third parties or transferred as security. The Buyer must notify us immediately in writing if an application for the opening of insolvency proceedings is filed or insofar as third parties (e.g., seizures) access the goods belonging to us. To the extent that the third party is not able to reimburse us for the judicial and extrajudicial costs of a lawsuit according to § 771 ZPO, the Buyer is liable for the loss incurred by us.',
        'seventh_content_3' => '7.3 In the event of a breach of contract by the Buyer, especially in the case of non-payment of the due purchase price, we are entitled to withdraw from the contract according to the legal provisions and/or to demand the return of the goods due to the retention of title. The request for return does not simultaneously include a declaration of withdrawal; rather, we are entitled to merely demand the goods back and to reserve the right to withdraw. In case the Buyer does not pay the due purchase price, we must have set the Buyer a reasonable deadline for payment without success before we can claim these rights. This only applies if such a deadline setting is not dispensable according to the legal provisions.',
        'seventh_content_4' => '7.4 The Buyer is obliged to take good care of the purchased item as long as the ownership has not yet been transferred to them. In particular, they are obligated to sufficiently insure it at their own expense against theft, fire, and water damage at the replacement value (note: only permissible for the sale of high-value goods). If maintenance and inspection work needs to be carried out, the Buyer must carry these out in a timely manner at their own expense.',
        
'eigth_title' => 'Warranty Claims of the Buyer',
'eigth_content_1' => '8.1 For the rights of the Buyer in case of material and legal defects (including incorrect and underdelivery as well as improper assembly/installation or defective instructions), the legal provisions apply unless otherwise specified below. This does not affect the statutory provisions on the sale of consumer goods (§§ 474 ff. BGB) and the rights of the Buyer from separately issued warranties, especially by the manufacturer.',
'eigth_content_2' => '8.2 We are not liable for defects that the Buyer knew or was grossly negligent in not knowing at the time of conclusion of the contract according to § 442 BGB.',
'eigth_content_3' => '8.3 Warranty claims of the Buyer exist only to the extent that the Buyer has complied with their statutory obligations to inspect and notify (§§ 377, 381 HGB). A written notification to us must be made immediately if a defect becomes apparent during delivery, upon inspection, or at any later point in time. Obvious defects must be reported in writing within [7] working days from delivery and non-obvious defects within the same period from discovery of the defects. If the Buyer fails to properly inspect and/or notify the defect, our liability for the defect not notified, or not notified in a timely or proper manner, is excluded according to the statutory provisions.',
'eigth_content_4' => '8.4 If the delivered goods are defective, we as the Seller have the choice of whether to remedy the defect (rectification) or to deliver an item free of defects (replacement delivery). If the type of supplementary performance chosen by us is unreasonable for the Buyer in the individual case, they may refuse it. However, we reserve the right to refuse supplementary performance under legal conditions. Moreover, we are entitled to make the supplementary performance dependent on the Buyer paying the due purchase price.',
'eigth_content_5' => '8.5 For the supplementary performance to be provided, the Buyer must give us the necessary time and opportunity. In particular, the Buyer must hand over the item for which a defect has been claimed for inspection purposes. In the event that we carry out a replacement delivery of an item free of defects, the Buyer must return the defective item to us according to the legal provisions. However, the Buyer does not have a claim to return.',
'eigth_content_6' => '8.6 In the case of warranty claims, SVControl has the right, at its discretion, to demand free rectification or exchange of the defective delivery/service, to have the defect remedied by a third party at the expense of the contractor, to terminate the contract immediately, or to demand a corresponding price reduction. The contractor bears all costs and expenses associated with the remedy of defects, including transport, travel, labor, and material costs as well as dismantling and installation costs at the agreed delivery location of the respective machine from SVControl',
'eigth_content_7' => '8.7 The Buyer has the right to remedy the defect themselves and demand reimbursement for the objectively necessary expenses if an urgent case exists (e.g., if operational safety is at risk or to avert disproportionately large damage). In the case of self-remedy, the Buyer must inform us immediately. In the event that we would be entitled to refuse supplementary performance according to the legal provisions, the Buyer does not have the right to self-remedy.',

'nineth_title' => 'Software Regulation',
'nineth_content_1' => '9.1 The Buyer guarantees that the reports, plans, concepts, drawings, compilations, analyses, and calculations created by SVControl as part of the order will be used exclusively for their own and the contractually agreed purposes and will not be published beyond this, unless this is contractually provided for. To the extent that the work results are protected by copyright, SVControl retains the copyright.',
'nineth_content_2' => '9.2 The Buyer commits to keeping all confidential information received in the context of using the software, including technical and business information, secret and not to disclose it to third parties. This obligation of confidentiality remains in effect even after the goods have been handed over.',

'tenth_title' => 'Choice of Law and Jurisdiction',
'tenth_content_1' => '10.1 For these General Terms and Conditions and the contractual relationship between us as the Seller and the Buyer, the law of the Federal Republic of Germany shall apply, excluding international uniform law, in particular the UN Convention on Contracts for the International Sale of Goods.',
'tenth_content_2' => '10.2 If the Buyer is a merchant within the meaning of the Commercial Code, a legal entity of public law or a special fund under public law, our place of business shall be the exclusive, and also the international, jurisdiction for all disputes arising directly or indirectly from the contractual relationship.',
'tenth_content_3' => '10.3 In addition, we are entitled to bring an action at the place of performance of the delivery obligation according to these General Terms and Conditions or a priority individual agreement, or at the general jurisdiction of the Buyer. This does not affect any overriding statutory provisions (exclusive jurisdictions).',
];